---
title: "Practice2"
author: "20180968 박서현"
date: '2020 10 13 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages('epitools')
#install.packages('rms')
#install.packages('vcdExtra')
#install.packages('MASS')
library(ggplot2)
library('epitools')
library('vcdExtra')
library(MASS)
```


## 2.11


데이터 생성


```{r}
Obama <- c(802, 53)
McCain <- c(34, 494)

data11 =rbind(Obama, McCain)
data11
```


신뢰구간


```{r}
oddsratio.wald(data11)
```


## 2.17


데이터 생성 


```{r}
y1 <- c(871, 347)
y2 <- c(821, 42)
y3 <- c(336, 83)

data17 <- data.frame(y1, y2, y3)
data17
```


(a)


```{r}
chisq.test(data17)
```


(b)


```{r}
out <- lm(y1 ~ . , data=data17)
out$residual
```


```{r}
stdres(out)
```


(c)


```{r}
chisq.test(data17)
```
p-value < 2.2×10<sup>−16</sup>   
0.05보다 p-value가 작다



## 2.21


데이터 생성


```{r}
y1 <- c(2, 2, 0, 0)
y2 <- c(4, 6, 1, 3)
y3 <- c(13, 22, 15, 13)
y4 <- c(3, 4, 8, 8)

data21 <- data.frame(y1, y2, y3, y4)
data21
```


(a)


```{r}
chisq.test(data21)
```


(b)


```{r}
chisq.test(data21)
```


## 2.23


(a)


```{r}
fisher.test(matrix(c(21, 2, 15, 3), ncol=2, byrow=TRUE), alternative="two.sided")
```

```{r}
fisher.test(matrix(c(21, 2, 15, 3), ncol=2, byrow=TRUE), alternative="greater")
```


```{r}
fisher.test(matrix(c(21, 2, 15, 3), ncol=2, byrow=TRUE), alternative="less")
```


(b)

```{r}
ormidp.test(21, 2, 15, 3, or=1)
```


## 2.28

처리 방법과 반응변수 간에 연관성이 강하기 때문에 문제가 발생한다.


## 2.29


(a)


```{r}
yes <- c(1230, 859)
no <- c(357, 413)

data29 = rbind(yes, no)
data29
```



(b)


```{r}
oddsratio.wald(data29)
```











